############################################################
#
# kingbase
#
############################################################
#<property name="hibernate.dialect" value="org.hibernate.dialect.KingbaseDialect" />

server:
  port: 8007
spring:
  application:
    name: user-service
  #  thymeleaf:
  #    check-template-location: false
  #    check-template: false
  datasource:
    url: jdbc:kingbase:// 192.168.208.117:54321/DB1
    #    url: jdbc:kingbase://192.168.1.25:54321/DB1
    #    url: jdbc:kingbase://192.168.16.117:54321/DB1
    #    username: SYSTEM
    #    password: SYSTEM
    username: SYSTEM
    password: SYSTEM
    driver-class-name: com.kingbase.Driver
mybatis:
  mapper-locations: classpath:**/mapper/*.xml
jwt:
  secret: XjuuZlKmzgGv8aVxQ0yLWbNjJpPqRtUwEiOoPpQqRrSt
  expiration: 36000000 # 10 hour